### ISSUE TITLE
Fixed path to Posix lib in Platform.Linux

### ISSUE THREAD

**Issue by NimoTh** [AirVPN/Eddie#12]
Is there a way to make the following reference relative or configurable via variable (like in Eclipse)?
src/Platform.Linux/Platform.Linux.csproj: lines 35 ff.:
`<Reference Include="Mono.Posix, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\Program Files (x86)\Mono-2.10.9\lib\mono\2.0\Mono.Posix.dll</HintPath>
    </Reference>`

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
