### ISSUE TITLE
compilation instructions (Linux)

### ISSUE THREAD

**Issue by themighty1** [AirVPN/Eddie#32]
Are there any compilation instructions for Linux x64?

**Comment by themighty1** [comment]
bump

**Comment by themighty1** [comment]
Finally found the link
https://airvpn.org/topic/12760-how-can-i-compile-the-source-code/
Would be nice to have this info in the README

**Comment by AirVPN** [comment]
You can find recent instruction support section in https://eddie.website

Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
