### ISSUE TITLE
Linux: don't rely on pre-built binary files

### ISSUE THREAD

**Issue by themighty1** [AirVPN/Eddie#34]
Right now, AirVPN ships with a few binary files:
stunnel, openvpn, libgdiplus.so.0, libMonoPosixHelper.so
Is there any compile-time switch to force the use of the same files which are already installed on my Linux system.

**Comment by Clodo76** [comment]
Binary files are in bundle only in portable edition.
.deb and .rpm use package dependencies system.
If you still want to use portable edition, simply delete the binary, Eddie will try to locate into your filesystem.

**Comment by baimafeima** [comment]
#73

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
