### ISSUE TITLE
AirVPN remains unresponsive on Mac OS X 10.11.5 (15F34)

### ISSUE THREAD

**Issue by michaeltarleton** [AirVPN/Eddie#35]
**Description**

AirVPN was working fine until a few months ago. Now when I open it, it just stays in the unresponsive state (ie. when I right-click the icon I always see the "force quit" option.)

**Reproduction Steps**
1. Open AirVPN
2. AirVPN is unresponsive

**Troubleshooting I've Tried**
- I tried installing v2.9 and v2.8 (installer pkg and standalone application copy to /Applications)
- Quitting Cisco AnyConnect VPN
- Clearing /Library/Caches and ~/Library/Caches

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
