### ISSUE TITLE
Windows10 missing tray icon

### ISSUE THREAD

**Issue by Zod-** [AirVPN/Eddie#39]
I've set up the client to start with windows, activate network lock and connect at startup.

Occasionally after closing the GUI after startup there will be no tray icon. With the GUI not accessible anymore and the tray icon gone there seems to be no way to get it back up again.

Starting the client again will just report that there already is a running instance. Is there any other way to bring the GUI back other than with the tray icon?

**Comment by Zod-** [comment]
This seems to be an issue with older windows versions too: https://airvpn.org/topic/16886-win10-airvpn-gui-main-windows-dissapeared-tray-works/

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
