### ISSUE TITLE
error compilation to linux

### ISSUE THREAD

**Issue by Pepetops** [AirVPN/Eddie#43]
Hi. I clone this git and try to make an airvpn compilation for linix.
I use opensuse TW and have installed mono,mono-devel, zlib zlib-devel and rpmbuild.
When I run build_linux.sh command I only see this error message: 
Eddie deployment v1.4
Arguments allowed: 'verbose' (show more logs), 'official' (signing files)
Platform: linux
Path base: /home/pepetops/Descargas/airvpn/airvpn-client
'rpmbuild' required. RPM installer will be unavailable.
Any idea?
Thanks

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
