### ISSUE TITLE
How to put it on ubuntu

### ISSUE THREAD

**Issue by Bhasski** [AirVPN/Eddie#48]
The project README is nothing but the name of the client. I am trying to run the script openvn in the linux_x64 but not helping. I am using Ubuntu 16.04 (xenial)

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
