### ISSUE TITLE
.deb: libmono-system-runtime2.0-cil missing

### ISSUE THREAD

**Issue by baimafeima** [AirVPN/Eddie#56]
I tried installing AirVPN via the .deb file on Ubuntu MATE. The installation failed to the following error: 
`Dependency is not satisfiable: libmono-system-runtime2.0-cil`
Could you include it in the .deb file and release a new version?

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
