### ISSUE TITLE
[macos][v2.12.4] Eddie freezes Mac OS Sierra on disconnecting and trying to reconnect

### ISSUE THREAD

**Issue by hkalan** [AirVPN/Eddie#61]
I am using following setup:

-Mac OS Sierra 10.12.4 
-Mac internal firewall set to off
-Little Snitch 3.7.4 

AirVPN Eddie 2.12.4 freezes occasionally, noticeably when disconnecting then trying to reconnect or when waking up from sleem, sometimes in latency check, sometimes in checking DNS/ Route, I have to force quit the Eddie and run it again, sometimes this helps, sometimes I have to restart the system to resolve the issue . I've tried a complete uninstall then reinstalling, but that didn't make any difference. Please help me resolve the issue.

**UPDATE (3 June 2017):**
Also reproducible in in Mac OS Sierra 10.12.5 with following setup:
-Mac internal firewall set to off
-Little Snitch 3.7.4
-Reinstalled Mac OS Sierra 10.12.5
-Reinstalled newest version of Mono Project from Mono Project website: 
http://www.mono-project.com/docs/getting-started/install/mac/
-Uninstalled and Installed a fresh copy of AirVPN (Eddie) 2.12.4 [also deleted AirVPN.ini]

After system is waked from standby/ sleep Eddie goes into cycle of connecting/ disconnecting loop (sometimes also freezes if doing latency tests). THE ONLY RESOLUTION SO FAR IS RESTARTING THE SYSTEM. closing/ force quitting eddie, disabling/ enabling WiFi, flushing the routes can't help in this situation (using following terminal commands):

sudo ifconfig en1 down
sudo ifconfig en1 up
sudo route -n flush

There is also two discussion thread in general AirVPN forum regarding to this issue:
https://airvpn.org/topic/16357-eddie-airvpn-client-freezes-after-sleep-osx/
https://airvpn.org/topic/22439-eddie-2124-freezing-osx/

**Comment by hajes** [comment]
I second that.

It is crashing by more often than Windows OS and it is getting annoying.

I close laptop lid and when I open again. Eddie is frozen and irresponsive.

As mentioned above by...disconnecting and hanging is usual issue.

**Comment by sseppola** [comment]
Same here, every time it goes into sleep the client freezes. After I restart Eddie it fails to connect, and ends up in repeating "Connecting", "Checking route don't match", "Routing checking failed" and then "Disconnecting" until I stop it.

**Comment by mikeappell** [comment]
Same problem here. There's more than one thread for this issue:

https://airvpn.org/topic/16357-eddie-airvpn-client-freezes-after-sleep-osx/

For others coming here with this issue, I made a post which has some steps to kill/restart Eddie without needing to reboot your computer:

https://airvpn.org/topic/16357-eddie-airvpn-client-freezes-after-sleep-osx/#entry62292

**Comment by bsabiston** [comment]
Every time.

**Comment by sseppola** [comment]
This has for some reason stopped happening to me a couple of days ago, although I haven't changed anything.

**Comment by freediverx** [comment]
This is a huge issue which is impacting all Mac users, and it has gone unresolved for months. Not only does the app freeze when trying to reconnect, but it **requires a complete system restart to resolve**. 

The only workaround I've found has been to revert back to v.2.11.15, which is troubling since it has issues of its own and may contain security vulnerabilities patched in later versions. The only advantage of this older version is that issues can be resolved by force quitting and then restarting the app, without requiring a restart of the computer.

AirVPN Support has gone out of their way to avoid acknowledging the issue, and they are advising users to install Tunnelblick as a workaround. In my case, I responded to Support by telling them that Tunnelblick is an unacceptable option, and the reason why I left my previous VPN service provider.

I'm concerned that the developers may be unaware of how serious this situation is. If this cannot be resolved soon I will be cancelling my service with AirVPN and advising others to do the same.

**Comment by hajes** [comment]
I left previous VPN ISP because it didn't work well with Amazon Video.

This one is no different + client issues.

It is not AirVPN fault because Edie is OpenSource and they don't develop it...they just listen to angry mob and cannot do anything about it.

**Comment by freediverx** [comment]
I think you misunderstand the relevance of "open source". The Eddie client is developed by AirVPN. It's their baby. The fact that they've made it open source is good because anyone is free to inspect the code and make sure their are no back doors or other vulnerabilities. But its open source status in no way relieves AirVPN of responsibility for the app.

**Comment by bsabiston** [comment]
I agree it is a pretty severe problem for something that we pay for monthly.  The 'open-source'-ness of it is a little misleading too, since the Mac version is developed using a development environment that is not free, and you have to have that before you can go in there and try to fix the problem yourself.  Unlike @freediverx thankfully I do not have to do a full restart, I can just force-quit and restart, but it is still annoying AF and I end up just not using the VPN...

**Comment by freediverx** [comment]
"Open source" means software whose source code is made available with a license in which the copyright holder provides the rights to study, change, and distribute the software to anyone and for any purpose. There's no requirement that open source software be developed using a free IDE. Regardless, Apple doesn't charge for Xcode (its IDE for developing Mac and iOS applications).

**Comment by bsabiston** [comment]
I didn't say there was a requirement that it be free.  I just meant to say that if someone, like me, gets the idea that they are just going to go in there and fix their problem for them then you are looking at paying for that IDE in addition to the actual work of fixing it.

**Comment by hajes** [comment]
that was the reason why I stoped to be ISP :-D

Whining users :-P

I understand your sorrow but try to think from ISP point of view:

1. people wan't everything for free and they won't get it they whine and go another ISP and whine again...it is cat mouse game

2. because people whine, most ISP keep cost to minimum.

You have to either choose state-of-art network HW and privacy or have average network HW and fancy client. You can't have both unless you users wish to pay like kings ;-)

I was always more Subaru guy...unique, simple and genial design, brutal performance and "rubbish" interior (UI,client) because once you strip all fancy stuff there must be foundation to begin with. If you have rubbish foundation, fancy stuff won't work anyway.

Tunnelblick works...so I use it now until they resolve issues with their client, which is only partially their fault because ever since Jobs entry to Valhalla...Apple sinks faster than Titanic. It is not only Edie that works weird, there is more apps working weird.

I guess it has something to do with latest Mac OS X because last real good one was 10.9 once they finally fixed memory issues. Ever since I see rapid decline and Windows style features such as SFOS (Self F*ck OS), freezing.

Sadly, my latest MBP was already installed with 10.12 crap and I fear what they release further.

**Comment by freediverx** [comment]
> I didn't say there was a requirement that it be free. I just meant to say that if someone, like me, gets the idea that they are just going to go in there and fix their problem for them then you are looking at paying for that IDE in addition to the actual work of fixing it.

Again, Xcode is free. The fact that something is open source doesn't mean "anyone" can go in a fix the problem. You need a computer, internet access, and some degree of programing expertise.

**Comment by freediverx** [comment]
> people wan't everything for free

The last time I checked, AirVPN is not a free service, nor even the cheapest. 

> Tunnelblick works

So does wiping your butt with tree bark. But some people insist on using toilet paper.

**Comment by hajes** [comment]
I hate to say I told you so...Apple cult is bunch of idiots. PERIOD. Over 80% of users use Apple products just for show off. PERIOD ;-)

I went for Apple because it is finally one UNIX-like distro that works and I don't need to fiddle with it like with Windows.

I don't belong to Apple cult and I never will be. For me it is just a tool for photography and I don't need another UNIX-like laptop. Furthermore, we all know Linux is poor choice for photographers because it is just unsupported Open Source project.

I don't care about more than 80% fancy crap supplied by Apple but their foundation works so I love to pay for something that works and lasts at least 5 years.

For me it was stability of UNIX, reduced performance but stability and I still can play with command line.

Since you whine about GUI you belong to that poser group because hardcore UNIX-like powerusers swear to command line and hate GUI :-P

It is Subaru analogy again...unless foundation works...GUI is just a cherry on cake...get over it or change ISP.

Do you have working VPN? if not, change ISP. If you need fancy GUI, go anywhere. I still have Private Internet Access account and their GUI is simple and it works. And they never whine about "illegal" stuff I supposedly downloaded.

**Comment by freediverx** [comment]
> Apple cult is bunch of idiots.
> because hardcore UNIX-like powerusers swear to command line and hate GUI

I don't recall anyone asking for the opinion of neckbeards living in their mothers' basements.

> you whine about GUI

My complaint about Tunnelblick was not about aesthetics - something that should be obvious to anyone after glancing at Eddie's Fisher Price UI. It's about functionality and convenience. Tunnelblick is a lowest common denominator product with limited features and inconvenient setup and configuration. Unlike some people, most of us here are looking for a VPN *appliance* that gets the job done without any bullshit tinkering. Tunnelblick fails spectacularly in that regard.

**Comment by hkalan** [comment]
AirVPN Support finally acknowledged only _"tiny number"_ of Mac Users are affected and in my earlier correspondent they mentioned it is not reproducible. We need to get traction and attention for this issue. Those _"tiny numbers"_ of Mac users that are affected please report the issue to AirVPN support and escalate it, post your results here and in the AirVPN Forum related to this issue (links below), even if we are just a "tiny number", this issue is very disruptive to our workflow  as paying customers this issue must be resolved in a timely manner.

**AirVPN Forum related Threads:**
https://airvpn.org/topic/16357-eddie-airvpn-client-freezes-after-sleep-osx
https://airvpn.org/topic/22439-eddie-2124-freezing-osx

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
