### ISSUE TITLE
Eddie not using custom OpenVPN path supplied (Mac OS)

### ISSUE THREAD

**Issue by ericdand** [AirVPN/Eddie#62]
I supplied an alternative OpenVPN path, but Eddie seems to be ignoring it.

To reproduce:
- Install the latest version of OpenVPN from their website (in my case, to `/usr/local/sbin`)
- Provide that path (`/usr/local/sbin/openvpn`) in the Preferences menu
- Restart Eddie
- Run `ps -ax` and check which `openvpn` instance is running; see `/Applications/AirVPN.app/Contents/MacOS/openvpn` still.

The change _is_ reflected in my `~/.airvpn/AirVPN.xml` config file.

A glance at the logs reveals nothing other than the fact that it's ignoring this path and just loading the built-in one anyway.

**Comment by ericdand** [comment]
Update: I just updated to the latest version of the client (now it's called `Eddie.app`), version 2.12.4. Still the same problem.

**Comment by baimafeima** [comment]
#73

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
