### ISSUE TITLE
Eddie.website TLS Certificate is Expired.

### ISSUE THREAD

**Issue by CanusDomini** [AirVPN/Eddie#63]
Just earlier today it was possible to download Eddie from the airvpn website and now the website is empty.  A link to the eddie changelog which I found on the airvpn forums 
https://eddie.website/changelog/?software=client&format=html returned the error : 

> eddie.website uses an invalid security certificate. The certificate expired on July 2, 2017 at 9:14 PM. The current time is July 3, 2017 at 2:02 AM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

Might this be why Eddie has disappeared from the website?

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
