### ISSUE TITLE
Investigate additional obfuscation options/stealth modes

### ISSUE THREAD

**Issue by baimafeima** [AirVPN/Eddie#64]
It would be great to support stealth mode to protect from deep packet inspection. The following options come to mind:

- TOR's obfsproxy
- XOR scrambling

**Comment by x0wllaar** [comment]
But they already have SSL and SSH specifically for this purpose. If anything, obfsproxy will look MORE suspicious due to it looking like a bunch of random noise on a random port. stunnel at least creates a browser-like traffic

**Comment by baimafeima** [comment]
Do you mean this? https://www.stunnel.org/index.html

**Comment by x0wllaar** [comment]
https://airvpn.org/ssl/ (this uses stunnel) or https://airvpn.org/ssh/

**Comment by baimafeima** [comment]
@x0wllaar `Obfs4` (https://github.com/Yawning/obfs4) worked great for me as an obfuscation option as part of the `Tor Browser Bundle`, not sure whether it can be implemented. It surely would be necessary if one wants to connect to Tor from China as access to the network is blocked entirely. Thanks for the links about SSL and SSH tunneling. Are there any other options that can be investigated? Are there any plans to support a new protocol such as `Wireguard`?

**Comment by AirVPN** [comment]
We are working about adding Wireguard support in both Eddie and AirVPN servers.

Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
