### ISSUE TITLE
[feature request] Minimize Eddie in the system tray in Linux

### ISSUE THREAD

**Issue by laspic** [AirVPN/Eddie#66]
In Linux (I'm under Ubuntu 14.04), I can't minimize Eddie in the system tray... and [it seems that I'm not alone](https://airvpn.org/topic/13191-linux-client-minimize-to-tray/?hl=%2Bsystem+%2Btray+%2Blinux).
It's very constraining to keep open the Eddie window for using AirVPN.

Can we imagine this kind of desktop integration coming soon ?
Thanks a lot.

**Comment by oberon2007** [comment]
I'm running Eddie in i3 and also find it very annoying that there seems to be no way to minimize, really?

**Comment by oberon2007** [comment]
Just tried in xfce and it's even worse here. When minimizing the the window, the app becomes completely invisible and there's no way to restore the window. In order to be able to access the GUI again you need to kill several instances of mono first and then re-launch it.
Certainly not a clean way...

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
