### ISSUE TITLE
OPEN VPN> OPTIONS IMPORT: adjustinglink_MTU 1625 and/or MTU 1627

### ISSUE THREAD

**Issue by scrumkick** [AirVPN/Eddie#68]
this line is in several eddie logs and also system logs.

It causes many disconnections and other problems

. 2017.09.16 20:12:23 - OpenVPN > OPTIONS IMPORT: adjusting link_mtu to 1625

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
