### ISSUE TITLE
exp. v2.13.6 - high CPU

### ISSUE THREAD

**Issue by atomGit** [AirVPN/Eddie#69]
experimental v2.13.6 is using a lot of CPU - this is the portable version (not portable mono) on linux mint 18.2

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
