### ISSUE TITLE
Eddie wont start on the archlinux 

### ISSUE THREAD

**Issue by MarkoShiva** [AirVPN/Eddie#71]
Eddie wont't start on Archlinux with kernel 4.13 I do have the mono package installed I tried using the portable version with GUI and it do not start up also tried using the AUR version changed the version number to  2.13.6 and it won't build because it missing some library also tried to build straight from the github and again it do not build and error is:

`:$ ./repository/build_linux.sh 
Cannot open assembly 'src/Deploy/bin/Release/Deploy.exe': No such file or directory.`

**Comment by baimafeima** [comment]
#73

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
