### ISSUE TITLE
IP6Tables usage? 

### ISSUE THREAD

**Issue by NovaCygni** [AirVPN/Eddie#72]
Why on earth does Network Lock attempt to use the IP6 Tables and not IPTables, IP6 Tables. uses Ip6.mapping in the kernel, which when enabled, connected to a AirVPN server, means Outgoing IP4 addresses attempt to use, and fail to use, Ip6 Addresses, due to the IP6 Tables in use. (* Feel free to test with Any IRC Server... *) 

1) AirVPN doesnt support IP6, thus
2) IPTables should be used not IP6Tables, because also,
3) IP6 Tables should be disabled at Kernel Level, for many, many, many Numerous reasons.

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
