### ISSUE TITLE
Offer Eddie without pre-compiled binaries to speed up inclusion into repositories

### ISSUE THREAD

**Issue by baimafeima** [AirVPN/Eddie#73]
Since over a year the [request](https://dev.solus-project.com/T492) of Eddie to be added to the Solus repositories is in limbo. On https://github.com/AirVPN/Eddie you stated that: 

> Eddie is written in C# with .Net/Mono framework. macOS edition use Xamarin.Mac. It is bundled with precompiled binary versions of OpenVPN, stunnel, plink/ssh and other tools for many platforms and architectures. If you don't want them, simply remove them and Eddie will locate it in your file system, or provide custom paths.

In order to maximize security and transparency for both distribution maintainers and end-users, and lastly to speed up this request, I am kindly asking you to release Eddie without any pre-compiled binaries.

**Comment by baimafeima** [comment]
It would also be great to provide a clear list of all dependencies. I find the instructions of the AzireVPN client straightforward and good to read: https://github.com/azirevpn/azclient

**Comment by baimafeima** [comment]
@AirVPN @Clodo76 @NimoTh Any updates on this?

**Comment by Clodo76** [comment]
Hi
Our .deb and .rpm release don't contain any pre-built binary. Only dependencies.
The portable edition (Linux) and all edition in Windows and macOS contain pre-built binary only to be user-friendly.
Note also that Eddie try to locate binaries: if you remove pre-built binaries, Eddie will try to search in your installed packages. 

About Solus, i honestly don't know/test it. I understand it use a specific package manager.
We also don't have yet an Arch package, currently managed by external people: https://aur.archlinux.org/packages/airvpn-bin/ .

I hope i can study Arch & Solus as soon as possible.

**Comment by Clodo76** [comment]
> It would also be great to provide a clear list of all dependencies. I find the instructions of the AzireVPN client straightforward and good to read: https://github.com/azirevpn/azclient
Here there are some info:
https://airvpn.org/topic/12760-how-can-i-compile-the-source-code/

We plan to completely separate Eddie from the AirVPN services, currently in beta (see [here](https://airvpn.org/topic/19909-eddie-with-other-providers-or-custom-openvpn-configuration-files/) ).
So we also plan to move Eddie-specific documentation to a dedicated website and expand it.

**Comment by in1t3r** [comment]
Well until your developers do not move to native Linux client without use of stupid mono I do not intend to use this VPN anymore there are others that offers a native linux clients and also its fairly easy using vpn and without them. 
I mean mono program that eats a 1gb of memory after few hours of usage pisses me off. This is not a windows game so that it need to be developed in stupid C# if you guys know port it out to use gtk or qt and then you will get back a lot of Linux users again for now I'm out of your network.

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
