### ISSUE TITLE
Dependences Need Updating

### ISSUE THREAD

**Issue by zero77** [AirVPN/Eddie#79]
All the third party dependences that Eddie uses are way out of date some are years out of date.

curl.exe
openvpn.exe
plink.exe
stunnel.exe
tap-windows.exe

That I know of but, there could be more that I have missed.

**Comment by jillmorinYXP** [comment]
You could use Squirrel or pyup-bot, to keep them up to date. @Clodo76 @AirVPN @NimoTh 
https://pyup.io/
https://github.com/Squirrel/Squirrel.Windows

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
