### ISSUE TITLE
Eddie 2.14.2 rpm package has broken dependencies, Fedora 27 x64

### ISSUE THREAD

**Issue by trochdewei** [AirVPN/Eddie#80]
Unable to install Eddie 2.14.2 because unmet dependencies

```
» rpm -ivh eddie-ui_2.14.2_linux_x64_rpm.rpm
warning: eddie-ui_2.14.2_linux_x64_rpm.rpm: Header V4 RSA/SHA1 Signature, key ID 400d7698: NOKEY 
error: Failed dependencies:                     
notify-send is needed by airvpn-2.14.2-0.x86_64
```

**Comment by duracellh** [comment]
Same issue in both Fedora 27 and Fedora 28 beta. It's odd because notify-send is already installed (provided by libnotify) and usable:

`    dnf provides '*/notify-send'
    Last metadata expiration check: 2:37:31 ago on Thu 26 Apr 2018 06:37:03 PM MDT.
    libnotify-0.7.7-4.fc27.x86_64 : Desktop notification library
    Repo        : @System
    Matched from:
    Filename    : /usr/bin/notify-send`

`# notify-send -v
notify-send 0.7.7`

**Comment by duracellh** [comment]
Saw the update in the changelog, so I can update the status for 2.14.4, I can't test in 27, but in Fedora 28 the rpm now pulls in libappindicator(pulls F27 version I think) and libindicator, install works correctly and everything works in the program, including notifications.

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
