### ISSUE TITLE
Allow lan/private? DNS Leak since my ISP is redirecting all plain DNS requests

### ISSUE THREAD

**Issue by Logmytech** [AirVPN/Eddie#82]
My ISP has been doing shady stuff like transparently proxying all DNS requests.

Maybe they are selling my data to advertisers or something much worse.

Steps of the problem. I'm not sure howaccurate my analysis is.

1) My router can't disable DNS and I have to compulsarily enter a valid IP.

2) My ISP intercepts any IP that the router uses for DNS.

3) Router might be using a custom port and proxying DNS that shows up as a LAN.

4) As I and I think Eddie has `Allow lan/private` enabled, DNS is allowed through the router.

Or might be that ISP DNS IP is on private network and `private`.

5) So, on IP leak DNS is leaked.

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
