### ISSUE TITLE
Confusing Message and setting for IPv6

### ISSUE THREAD

**Issue by Logmytech** [AirVPN/Eddie#83]
The message that is show when IPV6 is set to disabled is confusing.

### About the IPV6 option in Advanced
What does the disable IPV6 option do? Does it disable IPV6 check? Does it disable IPV6?
What does None do?

### About the popup about IPV6
Does it say that Eddie is incapable of doing IPV6 and leaks are likely?
Does it say it's going to disable IPV6?
Does it say IPV6 option(above) has been set so that leaks occur?

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
