### ISSUE TITLE
gksu isn't in Ubuntu 18.04 "bionic" repositories

### ISSUE THREAD

**Issue by quendil** [AirVPN/Eddie#85]
As i understood it has been replaced by pkexec. For now I think airvpn is not compatible with Ubuntu 18.04.
Trying to install airvpn with apt : 
> The following packages have unmet dependencies:
>  airvpn : Depends: gksu but it is not installable

**Comment by jyutzio** [comment]
I have found a successful method to install the client without gksu.

**If you have already tried to unsuccessfully install airpvn, first run the following command:**
```
sudo apt --fix-broken install
```

1.  Download the experimental version (2.14.3) from https://airvpn.org/linux/ 
2.  Install dependencies using the following command:
```
sudo apt install libc6 mono-runtime mono-utils libmono-system-core4.0-cil libmono-system-windows-forms4.0-cil openvpn stunnel4 curl
```
3. Install the client ignoring gksu using the following command:
```
sudo dpkg -i --ignore-depends=gksu /path/to/eddie-ui_2.14.3_linux_x64_debian.deb
```

Enjoy using the AirVPN client on 18.04 :)

Credit to corrado from the airvpn forums for this information.
https://airvpn.org/topic/26403-eddie-client-does-not-work-in-ubuntu-1804/

**Comment by AirVPN** [comment]
GKSU not used anymore in latest versions.

Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
