### ISSUE TITLE
portable GUI 2.17.2, 2.16.3, etc. HIGH CPU!

### ISSUE THREAD

**Issue by atomGit** [AirVPN/Eddie#91]
Linux without Mono - Mint, Manjaro, doesn't matter - CPU usage is crazy with eddie portable

complaints all over the place about this

when the hell is the 3. branch going to get released with a NATIVE Linux GUI?

been a customer of Air for over 2 years now - 2 years waiting and waiting for a non Mono client

ready to dump Air as a result

**Comment by ecogit** [comment]
I don't want to dump, but waiting for native Linux GUI nonetheless

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!

**Comment by boydthomson** [comment]
Nope.  This is still an issue in 2023.
