### ISSUE TITLE
network lock doesnt work iptables v1.6.1

### ISSUE THREAD

**Issue by Guilmort** [AirVPN/Eddie#92]
Hello
Network lock doesn't work at all Ubuntu 18.04 + iptables v1.6.1 + eddie ui 2.16.3
When I select deactivate network the buttons becomes green and an iptables -vL show that iptables are set correctly to avoid connections outputs except on VPN servers.
However once connected, iptables are reset to the normal configuration and the sames remains when I stop or brutally kill eddie. This means there is no protection at all :(

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
