### ISSUE TITLE
[macOS] Cannot connect to the internet after long hibernation

### ISSUE THREAD

**Issue by jimrobertson19** [AirVPN/Eddie#94]
Hey,
I'm running Mac OS X El Capitan.

I updated to the newest version of Eddie maybe two weeks ago and since then I've been having some trouble since installing the new version.

It seems to concern especially mornings when my Macbook has been in hibernation for the whole night. When I open the Macbook, Eddie is unable to connect to any VPN server. I have Network Lock on so the internet doesn't work. Even when I close Eddie, there is no internet connection available. Only when I then restart Eddie am I able to connect to a VPN and then the internet connection will come back online.

**Comment by jimrobertson19** [comment]
Actually I just left the lid of the laptop open the whole night and the same thing happened! So not connected to hibernation it seems!

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
