### ISSUE TITLE
Reconnect fails when lock is active

### ISSUE THREAD

**Issue by wvdvegt** [AirVPN/Eddie#98]
When i activate the lock, connect, disconnect a reconnect fails (it says it's 'Checking route IPv4' or IPv6 and finally disconnects when this fails and reconnects again).

In order to reconnect i need to re-activate the lock (deactivate&activate).

The issue seems to happen when IPv6 and IPV4 are both enabled. The issue is not present (it seems) if only IPv4 is selected (although the logging shows both IPv4 and IPv6 are checked for DNS leaks)

Using the Eddy-UI (2.16.3) and latest Windows 10 version fully patched.
Settings pretty default.

**Comment by AirVPN** [comment]
Closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
Please reopen if you still encounter this issue with the latest stable version.
If it’s an enhancement and hasn’t been taken on for so long, please re-submit.

Thank you!
